### ISSUE TITLE
exception after writing mesh in graph_to_mesh

### ISSUE THREAD

**Issue by terramars** [schillij95/ThaumatoAnakalyptor#29]
Saved mesh to /home/elliot/scrolls/dl.ash2txt.org/full-scrolls/Scroll1/PHercParis4.volpkg/surface_points/point_cloud_colorized_verso_subvolume_blocks/1781_2962_200/mesh_0.obj
Traceback (most recent call last):
  File "/home/elliot/miniconda3/envs/thaumato/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/elliot/miniconda3/envs/thaumato/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/elliot/scrolls/ThaumatoAnakalyptor/ThaumatoAnakalyptor/graph_to_mesh.py", line 1737, in <module>
    walk.unroll(fragment=args.fragment, debug=args.debug, continue_from=args.continue_from, z_range=z_range, angle_step=args.angle_step, z_spacing=args.z_spacing)
  File "/home/elliot/scrolls/ThaumatoAnakalyptor/ThaumatoAnakalyptor/graph_to_mesh.py", line 1686, in unroll
    split_mesh_paths, stamp = self.split(mesh_path, split_width=self.split_width, fresh_start=(continue_from <= 6), stamp=stamp)
  File "/home/elliot/scrolls/ThaumatoAnakalyptor/ThaumatoAnakalyptor/graph_to_mesh.py", line 1624, in split
    splitter = MeshSplitter(mesh_path, umbilicus_path, self.scale_factor)
TypeError: MeshSplitter.__init__() takes 3 positional arguments but 4 were given

not sure what the current pipeline is, i'm doing the following : 

instances_to_graph
graph_problem
instances_to_graph --create_graph
graph_to_mesh using ...BP_solved.pkl

i want to update the readme with the correct meshing pipeline, but it seems like i'm still missing something.

the steps i think need to take place after graph_to_mesh : 

slim_uv
large_mesh_to_surface

**Comment by schillij95** [comment]
hi terramars,
flattening with slim_uv happens during graph_to_mesh.
the next step afterwards would be to either use large_mesh_to_surface or mesh_to_surface depending on the size of your segmentation.

**Comment by schillij95** [comment]
thank you for the heads up about the issue with the MeshSplktter initialization.
